<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<NoWarn>CS1591</NoWarn>
		<Version>10.0.0</Version>
		<AssemblyVersion>10.0.0.0</AssemblyVersion>
		<FileVersion>10.0.0.0</FileVersion>
		<Description>
			EFxceptions is a .NET library that captures the exceptions thrown by Entity Framework
			from a SQL Server database and converts them into meaningful, domain-friendly exceptions.
			This package specifically targets Microsoft.EntityFrameworkCore 10.0.7.
		</Description>
		<Copyright>Copyright (c) The Standard Community</Copyright>
		<Authors>Hassan Habib</Authors>
		<Company>The Standard Community</Company>
		<NeutralLanguage>en</NeutralLanguage>
		<PackageProjectUrl>https://github.com/hassanhabib/EFxceptions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/hassanhabib/EFxceptions</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Exceptions EntityFramework EFCore SqlServer</PackageTags>
		<PackageReleaseNotes>Upgrade to net10 and targeting Microsoft.EntityFrameworkCore 10.0.7</PackageReleaseNotes>
		<PackageIcon>EFxceptions.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\EFxceptions.Shared\License.txt" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\EFxceptions.Shared\Resources\EFxceptions.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EFxceptions.Core\EFxceptions.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>EFxceptions.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
